name: chatgpt
description: "A ChatGPT & DALL·E App created using OpenAI API in Flutter and using MobX as state management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.2.0+2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  gif: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  mobx: ^2.3.0+1
  provider: ^6.1.1
  speech_to_text: ^6.5.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  # flutter_scripts: ^0.0.3
  hive_generator: ^2.0.1
  lint: ^2.3.0
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/gif/
    - assets/png/
    - assets/svg/

  fonts:
    - family: GtPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
# scripts:
#   build_store: dart run build_runner build --delete-conflicting-outputs
#   build_apk release: flutter build apk --release
